export const types = {
    PRODUCTS_REQUEST: 'PRODUCTS_REQUEST',
    PRODUCTS_FAILURE: 'PRODUCTS_FAILURE',
    PRODUCTS_SUCCESS: 'PRODUCTS_SUCCESS',
    PRODUCTS_PRELOAD: 'PRODUCTS_PRELOAD',
    PRODUCTS_LOADMORE: 'PRODUCTS_LOADMORE'
}
